[package]
name = "rofi-comm"
version = "0.1.0"
authors = ["Misha Farber Brodsky <taco@mailo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rofi = "0.2.2"
serde = "1.0.116"
serde_json = "1.0.57"
